document.write( '<nav class=\"navbar navbar-expand-md navbar-dark fixed-top bg-dark\">\n' );
document.write( '    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarsExampleDefault\" aria-controls=\"navbarsExampleDefault\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n' );
document.write( '        <span class=\"navbar-toggler-icon\"></span>\n' );
document.write( '    </button>\n' );
document.write( '  \n' );
document.write( '    <div class=\"collapse navbar-collapse\" id=\"navbarsExampleDefault\">\n' );
document.write( '        <ul class=\"navbar-nav mr-auto\">\n' );
document.write( '            <li class=\"nav-item active\">\n' );
document.write( '                <a class=\"nav-link\" href=\"index.html\">Home <span class=\"sr-only\">(current)</span></a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"about.html\">Skills</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"about.html\">About</a>\n' );
document.write( '            </li>\n' );
document.write( '        </ul>\n' );
document.write( '    </div>\n' );
document.write( '</nav>' );
